### ISSUE TITLE
Lines that wrap gets more than one line number

### ISSUE THREAD

**Issue by davidolrik** [lijyze/obsidian-advanced-codeblock#1]
As seen in this screenshot, line 8 wraps because it is too long to display on one line causing the wrapped line to get line number 9, instead of the real line number 9.

All the following lines are pushed down except for the last one which is missing a line number.

![CleanShot 2022-06-04 at 14 56 41@2x](https://user-images.githubusercontent.com/1990/172000031-ba42920b-ecf0-4acb-82f5-42db94cc22de.png)

In edit mode, Obsidian handles it correctly and adds a gap in the line numbers as seen here:

![CleanShot 2022-06-04 at 14 59 41@2x](https://user-images.githubusercontent.com/1990/172000132-e774ab61-9547-464a-b206-d498da28895a.png)

**Comment by lijyze** [comment]
Update to version 1.0.2, it will works well.

**Comment by davidolrik** [comment]
Looks good initially, but if you resize the window or otherwise increase or decreases the line length, the line numbers are stuck in their initial configuration.

Maybe there is a resize event you could listen to and then re-render?

**Comment by lijyze** [comment]
I have release version 1.0.3, I'm sure it should display correctly.

Thank you for you feedback.
