### ISSUE TITLE
指定行高亮切换阅读/源码模式未生效

### ISSUE THREAD

**Issue by russell662** [lijyze/obsidian-advanced-codeblock#11]
在修改指定的行号后例如`cpp {1,2}`改为`cpp {1,2,3}`，切换阅读模式时该修改未生效，必须重新打开文件

插件版本：v1.1.5
Obsidian版本：v1.4.13

**Comment by lijyze** [comment]
在说明里面说过了，只改参数的情况下必须重新打开。
obsidian的缓存逻辑把 ````language` 后面的东西排除在外了，只修改参数会认为内容没有任何变更不会重新渲染。
