### ISSUE TITLE
A bit confused

### ISSUE THREAD

**Issue by sophosukps** [lijyze/obsidian-advanced-codeblock#3]
Sorry if I am being a bit thick, but do I need to add

nums {1, 4-6, 8}

After the language? If so, what do the number represent. I copied your code and it worked fine, but not in Live Preview. Is that right?

This is a great plugin.

**Comment by lijyze** [comment]
Usage: https://github.com/lijyze/obsidian-advanced-codeblock/blob/main/README.md#usage

This plugin can only work in preview mode for now, I'm work on make it available in live preview mode.
