### ISSUE TITLE
Plugin not rendering changes for codeblocks nested inside blockquotes

### ISSUE THREAD

**Issue by mawev** [lijyze/obsidian-advanced-codeblock#5]
Hey, I have a few codeblocks nested inside blockquotes and callouts. The plugin however, don't seem to render the code block changes inside the blockquotes :

![image](https://user-images.githubusercontent.com/67217921/193757680-0657d8f3-52d9-4ab9-8f16-ba76ab074fc6.png)

![image](https://user-images.githubusercontent.com/67217921/193757693-bebdcc9f-e9a2-4041-9d3f-f0840b8964ec.png)

**Comment by lijyze** [comment]
It seems work well to me.
Generally, if you don't change your code after you add plugin param to code blocks, obsidian suppose your code has nothing changed, and render preview view with cache. So you need to add or remove something from your code to make obsidian rerender code block. Or you can just reopen the file.
