### ISSUE TITLE
Line numbers and line highlights only work in live preview

### ISSUE THREAD

**Issue by J-Howard** [lijyze/obsidian-advanced-codeblock#6]
Like the title suggests, displaying line numbers and line highlights is exclusively working in live preview, but does not work in "read" mode. 
From looking at past documentation it sounds like it originally worked in read mode, then you added support for live preview, but now it's only working in the latter.

**Comment by lijyze** [comment]
Dose it work after reload obsidian ?

**Comment by J-Howard** [comment]
@lijyze it unfortuantely does not. I have done a force reload while the application is open as well as a full restart of the app numerous times. The underlying function remains the same where "read" mode does not function.

**Comment by J-Howard** [comment]
@lijyze turns out it was conflicting with another theme I was using, and after swapping this issue is no longer present.
