### ISSUE TITLE
"Line Number" Display Bug in Reading View

### ISSUE THREAD

**Issue by vanbang9710** [lijyze/obsidian-advanced-codeblock#7]
It doesn't align
![image](https://user-images.githubusercontent.com/52906188/216981165-de7ed258-f800-429e-bf7d-c4d3c656a239.png)

The Code:
```js nums {1, 4-6}
TASK
WHERE !completed
SORT created ASC
LIMIT 10
GROUP BY file.link
SORT rows.file.ctime ASC
```
Live Preview
![image](https://user-images.githubusercontent.com/52906188/216980762-72910147-bcaa-4020-817f-051831254d26.png)

**Comment by bluesky5837645** [comment]
I change margin-top value in the style.css in <your_note_folder>/.obsidian/plugins/obsidian-advanced-codeblock/  as shown as below. Changing it into zero works for me.  
![image](https://user-images.githubusercontent.com/43314593/217148722-6cce750a-f640-4fc5-bcf7-d0dc7df73d5c.png)

**Comment by vanbang9710** [comment]
Thank you. This solves the problem
